<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN FD_TransactionFraudDetect
 */

require_once 'include/SugarObjects/templates/sale/Sale.php';

class FD_TransactionFraudDetect_sugar extends Sale {
    public $new_schema = true;
    public $module_dir = 'FD_TransactionFraudDetect';
    public $object_name = 'FD_TransactionFraudDetect';
    public $table_name = 'fd_transactionfrauddetect';
    public $importable = false;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $commentlog;
    public $commentlog_link;
    public $locked_fields;
    public $locked_fields_link;
    public $sync_key;
    public $fd_transactionfrauddetect_type;
    public $lead_source;
    public $amount;
    public $amount_usdollar;
    public $date_closed;
    public $next_step;
    public $sales_stage;
    public $probability;
    public $currency_id;
    public $base_rate;
    public $currency_name;
    public $currency_symbol;
    public $currencies;
    public $outcome;
    public $status;
    public $ttl_fraud_check;
    public $score;
    public $street;
    public $city;
    public $last_name;
    public $state;
    public $postal_code;
    public $dob;
    public $occupation;
    public $txn_num;
    public $cc_last_6;
    public $cc_month_year;
    public $ecomm_email;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}
